#!/usr/bin/env bash

# Function to check and print factors of a number

checkFactor() {
  if [ $# -ne 3 ]; then
    args=("$@")
    count=0
    num2=1
    for a in "${args[@]}"; do
      if [ $count -gt 1 ]; then
        num2=$(echo "$a*$num2" | bc)
      fi
      count=$((count + 1))
    done
  else
    num2=$3
  fi

  num1=$2
  num=$(echo "$1" | tr ':' '=')

  if [ "$(echo "$num2 > $num1" | bc)" -eq 1 ]; then
    temp=$num1
    num1=$num2
    num2=$temp
  fi

  echo "$num$num1*$num2"
}

if [ $# -ne 1 ]; then
  echo 'Usage: factors <file>'
  exit 1
else
  while read -r i; do
    result=$(factor "$i")
    checkFactor $result
  done < "$1"
fi
