#!/usr/bin/env bash

factorize()
{
	if [ $# -ne 3 ];
	then
		args=("$@")
		count=0
		prime2=1
		for a in ${args[@]};
		do
			if [ $count -gt 1 ];
			then
				prime2=$(bc <<< "$a * $prime2")
			fi
			count=$((count + 1))
		done
	else
		prime2=$3
	fi

	prime1=$2
	number=${1//:}

	r=$(echo "if($prime2 > $prime1) 1 else 0" | bc)

	if [[ $r -eq 1 ]];
	then
		temp="$prime1"
		prime1="$prime2"
		prime2="$temp"
        fi

	echo "$number=$prime1*$prime2"
}

if [ $# -ne 1 ]
then
	echo 'Usage: factors <file>'
	exit 1
else
	while read i
	do
		r=$(factor "$i")
		factorize $r
	done < "$1"
fi
