#!/usr/bin/python3

# rsa
import sys

def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize_rsa(number):
    for divisor in range(2, number):
        if number % divisor == 0 and is_prime(divisor) and is_prime(number // divisor):
            return divisor, number // divisor

if len(sys.argv) != 2:
    print("Usage: rsa <file>")
    sys.exit(1)

input_file = sys.argv[1]

with open(input_file, 'r') as file:
    for line in file:
        number = int(line)
        p, q = factorize_rsa(number)
        print(f"{number}={p}*{q}")
