#!/usr/bin/python3
import math
from sys import argv

def get_factors_of():
    with open(argv[1]) as f:
        for number in f:
            num = int(number)
            poss_p = math.floor(math.sqrt(num)) 

            if poss_p % 2 == 0: # Only checks odd numbers, it reduces time by orders of magnitude
                poss_p += 1
            while poss_p < num:
                if num % poss_p == 0:
                    print("{}".format(poss_p)
		else:
		    poss_p += 2
		    print("{}".format(poss_p)


if __name__ == "__main__":
    get_factors_of()
